### ISSUE TITLE
More precision is needed here

### ISSUE THREAD

**Issue by ashwinarora** [The-Poolz/Locked-pools#160]
Please change 1000 to 10**18.

https://github.com/The-Poolz/Locked-pools/blob/5261a59a03c402146a40ecd67d78cf0dd6246ff2/contracts/LockedDealV2.sol#L18

**Comment by YouStillAlive** [comment]
We need to test the difference precision calculation.

**Comment by Lomet** [comment]
> We need to test the difference precision calculation.

Please update with the results of the test

**Comment by YouStillAlive** [comment]
In most cases, it will take the same amount of time to calculate **1 token (1e18)** using the two formulas. It is because of this that we have not seen this issue before. But if we need **1,157 tokens** or **2,872 tokens**, we will have problems with the ideal calculation. If we have an example, the end time is 3 months or more and 10e18 tokens have been deposited into the pool. The case `10**18` is counted every second, while `*1000` is counted at larger intervals like 20 minutes etc.

**Comment by Lomet** [comment]
let's set it to 10e18 - but as the default value of a variable. that can be changed by the admin.

new deploy - here we come !!!

**Comment by Lomet** [comment]
still want to know the formula to how to calculate the "tick" time (what unit of time makes the change)
